### ISSUE TITLE
Importing and Initializing After Installation

### ISSUE THREAD

**Issue by bencomer** [cog-imperial/GPdoemd#1]
I've been trying to install and test this code, however I've run into a few issues. Perhaps I'm making some simple mistakes, please let me know.

1. `gp_grief` is listed as optional, but it seems not to run without it
2. `gp_grief` itself does not tell you how to install it (I assumed you just add it to your PYTHONPATH, it seemed to work)
3. when running the command `from GPdoemd.models import GPmodel` found in the documentation to initialize a model, I get the error "Could not import GPGriefModel - ensure gp_grief package is installed." I had installed `gp_grief` to the best of my knowledge (`import gp_grief.models` does run.) This error comes from a `try / except` block in `model/__init.py__`. When I removed the code from this block I get the error "from gp_grief.models import GPGriefModel as GPGModel  ImportError: cannot import name GPGriefModel" in line 30 of `gp_grief_model.py`. It looks like there is no class/function in `gp_grief.models` named ` GPGriefModel`. There are several models in this file, which one is meant to be imported in this line? (I see `GPweb_transformed`,`GPweb`,`GPGrief`,`GPRegression`, and `BaseModel`)

**Comment by scwolof** [comment]
I'm sorry to hear you're having problems running the code!

1. When you say it doesn't seem to run without `gp_grief`, can you be more specific? Is it installation of GPdoemd that fails? Does it throw an error message?

2. Yes, sorry, I should've included installation instructions for the forked `gp_grief` package. I would recommend installing it with pip, same as with GPdoemd: 
`pip install git+https://github.com/scwolof/gp_grief` .

3. Have you made sure to install [my fork](https://github.com/scwolof/gp_grief) of the `gp_grief` package, and not the original version?

**Comment by bencomer** [comment]
Thanks for the quick reply!

1. when I follow the installation instructions on github and just run `from GPdoemd.models import GPModel` I get this same error "Could not import GPGriefModel - ensure gp_grief package is installed." When I saw this message I went straight to google to find this package and missed the documentation saying to use your fork.

Your fork of `gp_grief` seems to have fixed the other issues. Some other notes I should make as well: 

In section 4 of the documentation, the first code that is listed is `from GPdoemd.models import GPmodel` the last item should be `GPModel` (note the case difference of the letters.) This gave me issues trying to import the package and getting no useful error until I noticed the slipped capital letter.

When I install the package vanilla I get an error "ImportError: cannot import name ties_and_remappings." Some [quick googling](https://github.com/SheffieldML/GPy/issues/555) revealed that installing `paramz-0.7.4` rather than `paramz-0.9.4` allowed things to import. Hopefully this doesn't throw any issues in the future.

**Comment by scwolof** [comment]
No worries! I'm glad the code is running now! 
Thank you for helping improve the package!

I will...
- clarify the error message to say that the **forked** gp_grief package should be installed.
- correct the documentation with `GPmodel` -> `GPModel`
- look into the `paramz-0.7.4` vs `paramz-0.9.4`. I haven't experienced any problems before. Very strange!
